#端口
server:
  port: 80
#应用名称
spring:
  application:
    name: pzhuweb
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true&serverTimezone=UTC
    username: root
    password: zfzfzf
mybatis:
  mapper-locations: classpath:mapper/*.xml
